# Generated by Django 5.1.2 on 2024-10-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('employer', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('typeOfWork', models.CharField(help_text='full-time, part-time, internship or other', max_length=128)),
                ('contract', models.CharField(help_text='work contract, civil contract or B2B', max_length=128)),
                ('operatingMode', models.CharField(help_text='remote, stationary or hybrid', max_length=128)),
                ('jobDescription', models.TextField()),
                ('requiredSkills', models.TextField()),
                ('dateAdded', models.DateField()),
                ('dateExpired', models.DateField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
