# Generated by Django 5.1.2 on 2024-10-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_appliedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='openedRoom',
            field=models.BooleanField(default=False),
        ),
    ]
