# Generated by Django 5.1.2 on 2024-10-13 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_openedroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='openedRoom',
        ),
    ]
