# Generated by Django 5.1.2 on 2024-10-13 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_job_openedroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='appliedUsers',
            new_name='joinedUsers',
        ),
    ]
