# Generated by Django 5.1.2 on 2024-10-13 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('jobs', '0007_rename_appliedusers_job_joinedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.channel'),
        ),
    ]
