# Generated by Django 5.1.2 on 2024-10-13 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('jobs', '0009_alter_job_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='channel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.channel'),
        ),
    ]
